###
POST http://127.0.0.1:8000/shop/
Content-Type: application/json

{
    "name": "Bakery Delights",
    "address": "123 Sweet St, Dessertville",
    "open_time": "2024-12-19T08:00:00"
}


###
GET http://127.0.0.1:8000/shop/1
Content-Type: application/json

###
POST http://127.0.0.1:8000/product/
Content-Type: application/json

{
    "name": "Croissant",
    "count": 50,
    "baked_date": "2024-12-19T06:00:00",
    "shelf_life": 2
}

###
GET http://127.0.0.1:8000/product/1
Content-Type: application/json